# This file was generated by GoReleaser. DO NOT EDIT.
cask "pairmux" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "142821827e38cc88f02ae04627ba73f8b8ca534a4f82876188354a26eb377f1c"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
    on_arm do
      sha256 "a8f5ee8b77d8e72418991820dbadc7c4b07df1de96902bb6b7aabb619fba6bdb"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8de6a1967fe5ed7cd4067561024cb2c782d84d3a2de90143b2c6895878964cd"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_linux_amd64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
    on_arm do
      sha256 "ac47c8216792f29f50d9d458773e2cd210215d66a984fbc70f8b0db232cf8fb4"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_linux_arm64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
  end

  name "pairmux"
  desc "Let AI agents drive interactive terminal programs on tmux, with live human handoff"
  homepage "https://pairmux.treeleaves30760.com"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "pairmux"
  manpage "man/pairmux.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pairmux"]
    end
  end

  # No zap stanza required

end
