# This file was generated by GoReleaser. DO NOT EDIT.
cask "pairmux" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "dccc777f65d9f0f06c9d2a06c7629811bf09df2b8f7f7a6c692a79d7a4d42af9"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
    on_arm do
      sha256 "b141a563e4d1169090621f4ed65818d578891ed63322da5248845083d58a0420"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
  end

  on_linux do
    on_intel do
      sha256 "8cf72a8c8f1765551654e9541b9b9e04ea5e716e8666efd001e1ef611947ea46"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_linux_amd64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
    on_arm do
      sha256 "c04986e0753faf242015552bb6563c7f404f140338487de399a5cb20e3116b7b"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_linux_arm64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
  end

  name "pairmux"
  desc "Let AI agents drive interactive terminal programs on tmux, with live human handoff"
  homepage "https://github.com/treeleaves30760/pairmux"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "pairmux"
  manpage "man/pairmux.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pairmux"]
    end
  end

  # No zap stanza required

end
