# This file was generated by GoReleaser. DO NOT EDIT.
cask "pairmux" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2a3cd99fd2208bdaa375aed2276b5ed6dcf9d9ebb0ca2c13d02b5c00f6d5d623"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
    on_arm do
      sha256 "094713ac232f7cdd93c1d299b742596ffad2c5db5754a0874432a1d99ab1e4da"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd47fef785908fca84e01283fc0c8e8124f7d6fc5e851e712424b6eb955d6898"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_linux_amd64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
    on_arm do
      sha256 "2474ca5c8879e1aae87f6dade22456e6efcc1a236ec3c33f1799b8c3b8fb5a9b"
      url "https://github.com/treeleaves30760/pairmux/releases/download/v#{version}/pairmux_#{version}_linux_arm64.tar.gz",
        verified: "github.com/treeleaves30760/pairmux/"
    end
  end

  name "pairmux"
  desc "Let AI agents drive interactive terminal programs on tmux, with live human handoff"
  homepage "https://github.com/treeleaves30760/pairmux"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "pairmux"
  manpage "man/pairmux.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pairmux"]
    end
  end

  # No zap stanza required

end
